id: P006888
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:28:53.301630
source_metadata:
  id: bdr:W3CN4672
  title: སྙན་ངག་མེ་ལོང་གི་འགྲེལ་པ་དབྱངས་ཅན་དགྱེས་པའི་རོལ་མཚོ།
  author: ''
  volumes:
    39606f04785b4e0bb92583400d9a6b3a:
      image_group_id: I3CN4674
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
